name:                raider-client
version:             0.1.0.0
github:              "sikfeng/raider-client"
license:             BSD-3-Clause
author:              "Cheong Sik Feng"
maintainer:          "sikfeng@gmail.com"
copyright:           "2024 Cheong Sik Feng"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sikfeng/raider-client#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- text
- websockets
- optparse-applicative
- hslogger

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - Connection

executables:
  raider-client-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raider-client
    - optparse-applicative
    - hslogger

tests:
  raider-client-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raider-client
